NewsConfigurationModule/Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Christoc.Modules.NewsConfigurationModule.Models
{
    public class News
    {
        public int IdNews { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string LifeDate { get; set; }
        public bool HasFile { get; set; }
        public string PathFile { get; set; }
        public DateTime CreatedDate { get; set; }
        public Attachment Attachment { get; set; }
        public string TitleOld { get; set; }
        public string Status { get; set; }
    }
}

NewsConfigurationModule/Controllers/NewsController.cs
using Christoc.Modules.NewsConfigurationModule.Models;
using Christoc.Modules.NewsConfigurationModule.Services;
using DotNetNuke.Web.Mvc.Framework.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Christoc.Modules.NewsConfigurationModule.Controllers
{
    public class NewsController : DnnController
    {
        private DataService DataService = null;
        Response Response = null;

        public NewsController()
        {
            DataService = new DataService();
            Response = new Response();
        }
        // GET: News
        public ActionResult Index()
        {
            List<News> lstNews = new List<News>();
            bool HasData = false;
            string Message = string.Empty;
            var response = DataService.GetNews();
            if (response.IsSuccess)
            {
                lstNews = (List<News>)response.Result;
                HasData = response.IsSuccess;
                Message = "";
            }
            else
            {
                lstNews = null;
                HasData = response.IsSuccess;
                Message = response.Message;
            }

            ViewBag.lstNews = lstNews;
            ViewBag.HasData = HasData;
            ViewBag.Message = Message;

            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id = 0)
        {
            News News = new News();
            bool HasData = false;
            string Message = string.Empty;
            var response = DataService.GetNewsById(id);
            if (response.IsSuccess)
            {
                News = (News)response.Result;
                HasData = response.IsSuccess;
                Message = "";
            }
            else
            {
                News = null;
                HasData = response.IsSuccess;
                Message = response.Message;
            }

            ViewBag.News = News;
            ViewBag.HasData = HasData;
            ViewBag.Message = Message;
            return View();
        }
    }
}

NewsConfigurationModule/Views/News/Create.cshtml
@{
    ViewBag.Title = "Create";
}


<link href="~/DesktopModules/MVC/NewsConfigurationModule/StyleSheet/datepicker.css" rel="stylesheet" />
<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />

<link href="~/desktopmodules/mvc/NewsConfigurationModule/StyleSheet/prettify.css" />
<link href="~/DesktopModules/MVC/NewsConfigurationModule/StyleSheet/bootstrap-wysihtml5.css" rel="stylesheet" />
<link href="~/desktopmodules/mvc/NewsConfigurationModule/StyleSheet/wysiwyg-color.css" rel="stylesheet" />


<div class="row">
    <div class="col-md-12">
        <h3>Crear Noticia</h3>
        <br />
        <br />
    </div>
</div>

<div class="alert alert-info" role="alert" id="div_alert_create">
    <i class='fa fa-info-circle' id="icon_create"></i> <span id="txt_mensaje_create"></span>
</div>

<div class="row">
    <div class="col-md-12">
        @Html.ActionLink("Regresar a Noticias", "Index", "News", new { }, new { @class = "btn btn-primary", @style = "color:#FFF" })
        <br />
        <br />
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <input type="hidden" id="idNews" value="0" />
        <div class="col-md-6">
            <div class="form-group">
                <label>Titulo</label>
                <input type="text" class="form-control" id="title" maxlength="40" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Fecha de Vigencia</label>
                <input type="text" class="form-control datepicker" id="lifeDate" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label>Descripción Corta</label>
                <textarea id="shortDescription" name="shortDescription" class="form-control" style="height:100px" maxlength="250"></textarea>
                <span class="text-danger" id="shortDescripcion_message"></span>
                <span class="text-info"></span>
            </div>

        </div>
        <div class="col-md-8">
            <div class="form-group">
                <label>Descripción Larga</label>
                <textarea class="form-control" id="longDescription" style="height:300px" maxlength="1500" name="longDescription"></textarea>
                <span class="text-danger" id="longDescripcion_message"></span>
                <span class="text-info"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label>Adjunto</label>
                <input type="file" id="attached" />
                <textarea rows="10" style="width: 98%;display:none;" class="" id="contentFile"></textarea>
            </div>
            <div class="form-group">
                <input type="button" value="Guardar" id="btn_createNews" class="btn btn-success btn-block" />
            </div>
        </div>
    </div>
</div>

<script>
    var urlIndex = '@Url.Action("Index", "News")';
</script>


<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/datepicker.js"></script>
<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/site.js"></script>

<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/wysihtml5-0.3.0.js"></script>
<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/prettify.js"></script>
<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/bootstrap-wysihtml5.js"></script>

<script src="~/desktopmodules/mvc/NewsConfigurationModule/Scripts/wysihtml5/parser_rules/advanced.js"></script>
<script src="~/desktopmodules/mvc/NewsConfigurationModule/Scripts/wysihtml5/parser_rules/simple.js"></script>

<script>
    $(function () {

        $('#longDescription').wysihtml5({
            events: {
                blur: function () {
                    var maxlen = parseInt($("#longDescription").attr('maxlength'));
                    var length = $("#longDescription").val().replace(/<[^>]*>?/g, '').length;
                    if (length <= maxlen) {
                        $("#longDescripcion_message").removeClass("text-danger").addClass("text-info");
                        $("#longDescripcion_message").html("Caracteres encontrados " + length);
                    }
                    else {
                        $("#longDescripcion_message").removeClass("text-info").addClass("text-danger");
                        $("#longDescripcion_message").html("<b>Caracteres encontrados " + length + ", caracteres aceptados son " + maxlen + " solamente</b>");
                    }
                }
            }
        });

        $('#shortDescription').wysihtml5({
            events: {
                blur: function () {
                    var maxlen = parseInt($("#shortDescription").attr('maxlength'));
                    var length = $("#shortDescription").val().replace(/<[^>]*>?/g, '').length;
                    if (length <= maxlen) {
                        $("#shortDescripcion_message").html("Caracteres encontrados " + length);
                        $("#shortDescripcion_message").removeClass("text-danger").addClass("text-info");
                    }
                    else {
                        $("#shortDescripcion_message").removeClass("text-info").addClass("text-danger");
                        $("#shortDescripcion_message").html("<b>Caracteres encontrados " + length + ", caracteres aceptados son " + maxlen + " solamente </b>");
                    }
                }
            }
        });
    })
</script>

NewsConfigurationModule/Views/News/Edit.cshtml
@{
    /**/

    ViewBag.Title = "Edit";
}

<link href="~/DesktopModules/MVC/NewsConfigurationModule/StyleSheet/datepicker.css" rel="stylesheet" />

<link href="~/desktopmodules/mvc/NewsConfigurationModule/StyleSheet/prettify.css" />
<link href="~/DesktopModules/MVC/NewsConfigurationModule/StyleSheet/bootstrap-wysihtml5.css" rel="stylesheet" />
<link href="~/desktopmodules/mvc/NewsConfigurationModule/StyleSheet/wysiwyg-color.css" rel="stylesheet" />

<div class="row">
    <div class="col-md-12">
        <h3>Editar Noticia</h3>
        <br />
        <br />
    </div>
</div>

<div class="alert alert-info" role="alert" id="div_alert_edit">
    <i class='fa fa-info-circle' id="icon_edit"></i> <span id="txt_mensaje_edit"></span>
</div>


<div class="row">
    <div class="col-md-12">
        @Html.ActionLink("Regresar a Noticias", "Index", "News", new { }, new { @class = "btn btn-primary", @style = "color:#FFF" })
        <br />
        <br />
    </div>
</div>

@if (!(bool)ViewBag.HasData)
{
    <h3>@ViewBag.Message</h3>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <input type="hidden" id="idNews" value="@ViewBag.News.IdNews" />
            <input type="hidden" id="titleOld" value="@ViewBag.News.Title" />
            <div class="col-md-6">
                <div class="form-group">
                    <label>Titulo</label>
                    <input type="text" class="form-control" id="title" value="@ViewBag.News.Title" max="40" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Fecha de Vigencia</label>
                    @{
                        var date = ((string)ViewBag.News.LifeDate).Split(' ')[0];
                        var lifeDate = date[2] + "/" + date[0] + "/" + date[1];
                    }
                    <input type="text" class="form-control datepicker" id="lifeDate" value="@date" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Descripción Corta</label>
                    <textarea id="shortDescription" class="form-control" style="height:100px" maxlength="250">@ViewBag.News.ShortDescription</textarea>
                    <span class="text-danger" id="shortDescripcion_message"></span>
                    <span class="text-info"></span>
                </div> 
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label>Descripción Larga</label>
                    <textarea class="form-control" id="longDescription" style="height:300px" maxlength="1500">@ViewBag.News.LongDescription</textarea>
                    <span class="text-danger" id="longDescripcion_message"></span>
                    <span class="text-info"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Adjunto</label>
                    <input type="file" id="attached" />
                    <textarea rows="10" style="width: 98%;display:none;" class="" id="contentFile"></textarea>
                </div>
                <div class="form-group">
                    <input type="button" value="Guardar" id="btn_editNews" class="btn btn-success btn-block" />
                </div>
            </div>
            @{
                var HasFile = (ViewBag.News.HasFile) ? 1 : 0;
            }
            <input type="hidden" id="hasFile" value="@HasFile" />
            @if (ViewBag.News.HasFile)
            {
                <div class="col-md-6">
                    <input type="hidden" id="pathFile" value="@ViewBag.News.PathFile" />
                    <h4>Imagen Actual</h4>
                    <div class="col-md-12">
                        <center>
                            <img src="@ViewBag.News.PathFile" class="img-responsive img-thumbnail" />
                        </center>
                    </div>
                </div>
            }
            <div class="col-md-12">

            </div>
        </div>
    </div>
}


<script>
    var urlIndex = '@Url.Action("Index", "News")';
</script>

<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/datepicker.js"></script>
<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/site.js"></script>

<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/wysihtml5-0.3.0.js"></script>
<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/prettify.js"></script>
<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/bootstrap-wysihtml5.js"></script>


<script>
    $(function () {
        $('#longDescription').wysihtml5({
            events: {
                blur: function () {
                    var maxlen = parseInt($("#longDescription").attr('maxlength'));
                    var length = $("#longDescription").val().replace(/<[^>]*>?/g, '').length;
                    if (length > maxlen) {
                        $("#longDescripcion_message").removeClass("text-info").addClass("text-danger");
                        $("#longDescripcion_message").html("<b>Caracteres encontrados " + length + ", caracteres aceptados son " + maxlen + " solamente</b>");
                    }
                    else {
                        $("#longDescripcion_message").removeClass("text-danger").addClass("text-info");
                        $("#longDescripcion_message").html("Caracteres encontrados " + length);
                    }
                }
            }
        });

        $('#shortDescription').wysihtml5({
            events: {
                blur: function () {
                    var maxlen = parseInt($("#shortDescription").attr('maxlength'));
                    var length = $("#shortDescription").val().replace(/<[^>]*>?/g, '').length;
                    if (length > maxlen) {
                        $("#shortDescripcion_message").removeClass("text-info").addClass("text-danger");
                        $("#shortDescripcion_message").html("<b>Caracteres encontrados " + length + ", caracteres aceptados son " + maxlen + " solamente </b>");
                    }
                    else {
                        $("#shortDescripcion_message").html("Caracteres encontrados " + length);
                        $("#shortDescripcion_message").removeClass("text-danger").addClass("text-info");
                    }
                }
            }
        });
    })
</script>

NewsConfigurationModule/Views/News/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="~/DesktopModules/MVC/NewsConfigurationModule/StyleSheet/datepicker.css" rel="stylesheet" />
<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">


<div class="row">
    <div class="col-md-12">
        <a href="http://www.tasisoft.com/tasinet2/Portals/0/Repositorios/Manuales_Usuario/Manual%20de%20Usuario%20-%20Modulo%20Noticias%20DNN.pdf" target="_blank">
            <i class="fa fa-download fa-3x"></i> Descargar Manual de Usuario
        </a>
    </div>
</div>
<br />

<div class="row">
    <div class="col-md-12">
        @Html.ActionLink("Crear Nueva Noticia", "Create", "News", new { }, new { @class = "btn btn-success", @style = "color:#FFF" })
        <br />
        <br />

        <div class="alert alert-info" role="alert" id="div_alert_delete">
            <i class='fa fa-info-circle' id="icon_delete"></i> <span id="txt_mensaje_delete"></span>
        </div>

        <table id="tbl_News" class="display datatable" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Titulo</th>
                    @*<th>Descripción corta</th>*@
                    <th>Fecha Vigencia</th>
                    <th>Fecha Creación</th>
                    <th>Tiene Imagen</th>
                    <th>Estatus</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @if ((bool)ViewBag.HasData)
                {
                    foreach (var i in ViewBag.lstNews)
                    {
                        <tr>
                            <td>@i.Title</td>
                            @*<td>@i.ShortDescription</td>*@
                            <td>
                                @{
                                    var lifeDate = i.LifeDate.Split(' ')[0];
                                }
                                <p>@lifeDate</p>
                            </td>
                            <td>@i.CreatedDate.ToString("dd/MM/yyyy hh:mm tt")</td>
                            <td>
                                @{
                                    var hasFile = (i.HasFile) ? "Si" : "NO";
                                }
                                <p>@hasFile</p>
                            </td>
                            <td>
                                @{
                                    var style = (i.Status == "Caducado") ? "lifeDate" : "text-success bg-success";
                                }
                                <p class="@style">@i.Status</p>
                            </td>
                            <td>@Html.ActionLink("Editar", "Edit", "News", new { id = @i.IdNews }, new { @class = "btn btn-primary", @style = "color:#FFF" })</td>
                            <td><button type="button" onclick="DeleteNewsById(@i.IdNews)" class="btn btn-danger">Eliminar</button></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>


<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/datepicker.js"></script>
<script src="~/DesktopModules/MVC/NewsConfigurationModule/Scripts/site.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script>
    LoadTable();
</script>